shopping = ["bread", "milk", "eggs", "sugar"]
shopping.append("butter")
print(shopping)
shopping.insert(1, "chocolate")
print(shopping)
shopping.extend(["jaggary","sauce"])
print(shopping)
shopping.remove("sugar")
print(len(shopping))
print(shopping)
print(shopping.index("eggs"))
shopping.reverse()
print(shopping)
shopping.sort()
print(shopping)
shopping1 = shopping.copy()
print(shopping1)
print(shopping)